apiVersion: v1
kind: Secret
metadata:
  name: wikijs-postgresql-secret
  namespace: wikijs
type: Opaque
data: #must be base64 encoded value
  POSTGRES_DB: <<POSTGRES_DB>> #
  POSTGRES_DB_HOST: <<POSTGRES_DB_HOST>>
  POSTGRES_USER: <<POSTGRES_USER>>
  POSTGRES_PASSWORD: <<POSTGRES_PASSWORD>>
